version: '3'
services:
  dev:
    image: hashicorp/middleman-hashicorp
    ports:
      - "4567:4567"
      - "35729:35729"
    volumes:
      - ./:/website
    command: ["bundle", "exec", "middleman", "server", "--bind-address", "0.0.0.0"]
