# Host to use for canonical URL generation (without trailing slash)
host: docs.nationalleadership.gov.uk

# Header-related options
show_govuk_logo: false
service_name: NLC Technical Documentation
service_link: https://docs.nationalleadership.gov.uk/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  Documentation: /

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
# ga_tracking_id: 

# google_site_verification:

# Multi-page options
multipage_nav: true
collapsible_nav: true

max_toc_heading_level: 3
